#!/usr/bin/zsh

file=$1
home=$HOME # preventing a change in actual $HOME
dir="$home/codeIt"

# if argument is null, then
if [ -z "$file" ]; then
    # Can only be used either in function or sourced scripts
    # ref : https://unix.stackexchange.com/a/138736
    echo "No file passed"
    return  
fi

# if dir does not exist make it
if [ ! -d $dir ]; then
    mkdir $dir
fi

# if exists change dir
cd "$home/codeIT"

# if file doesn't exists, make one with predefined text
if [ ! -f $file ]; then
    cp "$home/dotfiles/fpp.txt" $file
fi

vi +10 $file
