#!/usr/bin/zsh

home=$HOME # preventing a change in actual $HOME
base_dir=$home/codeIt

opt_dir=${1:-"-c"} #default is competing directory
file=${2:-"test.cpp"} #default file that will open
quest=${3:-"testing"}

# check if base_dir exit, otherwise create it
if [ ! -d $base_dir ]; then
    mkdir $base_dir
fi
# check if argument is empty

if [ "$opt_dir" = "-c" ]; then
    if [ ! -d $base_dir/compete ]; then
        mkdir $base_dir/compete
    fi
    dir=$base_dir/compete
elif [ "$opt_dir" = "-a" ]; then
    if [ ! -d $base_dir/algo ]; then
        mkdir $base_dir/algo
    fi
    dir=$base_dir/algo
elif [ "$opt_dir" = "-v" ]; then
    if [ ! -d $base_dir/virtual_contest ]; then
        mkdir $base_dir/virtual_contest
    fi
    dir=$base_dir/virtual_contest
elif [ "$opt_dir" = "-p" ]; then
    if [ ! -d $base_dir/practice ]; then
        mkdir $base_dir/practice
    fi
    dir=$base_dir/practice

fi

# change to dir (based on options above)
cd $dir 
# if file doesn't exists, make one with predefined text
if [ ! -f $file ]; then
    cat >> $file << END
//Question : $quest
END
    cat ~/Projects/HubProj/bash/dotfiles/fpp.txt >> $file
    vi +15 $file
else
    vi $file
fi
        
